# docker-compose version
version: '3'

services:
  kintone:
    container_name: kintone
    build: . # specify the directory of the Dockerfile
    volumes:
      - ./:/app
    ports:
    - 3000:3000
    tty: true